<?php 
$questcat3 = $this->category->getSeo()->getQuestioncat3();
$answecat3 = $this->category->getSeo()->getAnswercat3();
$searchp = array("<p>", "</p>");
$removep   = array("", "");
$newquestcat3 = str_replace($searchp, $removep, $questcat3);
?>	

<div class="accordion-item">
    <div class="accordion-header" id="headingOne3">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#collapseOne3" aria-expanded="false" aria-controls="collapseOne3">
            <span class="number-title">3.</span><span class="me-3"><span>🥇 </span> <?php echo $newquestcat3;?></span>
        </button>
    </div>
    <div id="collapseOne3" class="accordion-collapse collapse" aria-labelledby="headingOne3"
        data-bs-parent="#accordionExample3">
        <div class="accordion-body">
        <?php echo $answecat3;?>
        </div>
    </div>
</div>