<?php $promoBlock = Fenix::getCollection('catalog/promo')->load('popular_products') ?>
<?php if ($promoBlock !== false): ?>
    <div class="hot-products" style="margin-top: 20px">
        <div class="hot-title">
            <div class="label">Горячие предложения</div>
            <div class="all"><a href="<?php echo $this->getUrl('gorjachie_predlozhenija') ?>">Показать все предложения</a></div>
        </div>
        <div class="products-list">
            <?php //Fenix::dump($promoBlock->getProducts()) ?>
            <?php foreach ($promoBlock->getProducts() AS $i => $_product): if ($i == 10) break; ?>
                <?php echo $this->partial('catalog/products/block.phtml', array('i' => $i, 'product' => $_product, 'category' => null)) ?>
            <?php endforeach ?>
        </div>
    </div>
<?php endif ?>
