<?php $req = Fenix::getRequest() ?>
<?php $orderInfo = Fenix::getCollection('checkout/order')->getOrderInfo() ?>
<?php $products  = Fenix::getCollection('checkout/order')->getProducts() ?>
           <?php foreach ($products AS $i => $_product) {
                    $totalCost += ($_product->getOrderUnitPrice() * $_product->getOrderQty());
                    $totalCost = number_format($totalCost, 2, ',', '');
                 } ?>
<?php 
if (strpos($_SERVER['REQUEST_URI'], '/ua') !== false) { 
				$lang = 'uk';
				
			} else { 
			$lang = 'ru';
			
			}
?>				 

<section style="text-align: center;">
    <h1 class="page-title"><span><?php echo Fenix::lang('Сожалеем, произошла ошибка платежа!') ?></span></h1>
    <article>
        <div class="order-data">
            <p><?php echo Fenix::lang('Не расстраивайтесь! Мы сохранили Ваш заказ и наши менеджеры с Вами свяжутся для уточнения способа оплаты и деталей заказа!') ?></p>
        </div>
        <div class="clearfix"></div>
    </article>
</section>
