<?php $products = Fenix::getModel('catalog/products')->getNewProduct() ?>
<?php $productsCollection = Fenix::getCollection('catalog/products')->setList($products)?>
<section class="one-column wrapper-980 popular-list" style="z-index:2;">
    <h1 class="page-title"><span>Новинки</span></h1>
    <article>
        <div class="products-list" style="position:relative;z-index:1;">
            <?php foreach ($productsCollection AS $i => $_product): ?>
                <?php echo $this->partial('catalog/products/block.phtml', array('i' => $i, 'step' => 4, 'product' => $_product)) ?>
            <?php endforeach ?>
            <div class="clearfix"></div>
        </div>
    </article>
</section>