
<?php 
$quest4 = $this->category->getSeo()->getQuestion4();
$answe4 = $this->category->getSeo()->getAnswer4();
$searchp = array("<p>", "</p>");
$removep   = array("", "");
$newquest4 = str_replace($searchp, $removep, $quest4);
?>	
<div class="accordion-item">
    <div class="accordion-header" id="headingOne4">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#collapseOne4" aria-expanded="false" aria-controls="collapseOne4">
            <span class="number-title">4.</span><span class="me-3"><span>🥇 </span> <?php echo $newquest4;?></span>
        </button>
    </div>
    <div id="collapseOne4" class="accordion-collapse collapse" aria-labelledby="headingOne4"
        data-bs-parent="#accordionExample4">
        <div class="accordion-body">
        <?php echo $answe4;?>
        </div>
    </div>
</div>