<?php 
$questcat1 = $this->category->getSeo()->getQuestioncat1();
$answecat1 = $this->category->getSeo()->getAnswercat1();
$searchp = array("<p>", "</p>");
$removep   = array("", "");
$newquestcat1 = str_replace($searchp, $removep, $questcat1);
?>	
<div class="accordion-item">
    <div class="accordion-header" id="headingOne1">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#collapseOne1" aria-expanded="false" aria-controls="collapseOne1">
            <span class="number-title">1.</span><span class="me-3"><span>🥇 </span> <?php echo $newquestcat1;?></span>
        </button>
    </div>
    <div id="collapseOne1" class="accordion-collapse collapse" aria-labelledby="headingOne1"
        data-bs-parent="#accordionExample1">
        <div class="accordion-body">
        <?php echo $answecat1;?>
        </div>
    </div>
</div>	