<?php 
$quest1 = $this->category->getSeo()->getQuestion1();
$answe1 = $this->category->getSeo()->getAnswer1();
$searchp = array("<p>", "</p>");
$removep   = array("", "");
$newquest1 = str_replace($searchp, $removep, $quest1);
?>

<div class="accordion-item">
    <div class="accordion-header" id="headingOne1">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#collapseOne1" aria-expanded="false" aria-controls="collapseOne1">
            <span class="number-title">1.</span><span class="me-3"><span>🥇 </span> <?php echo $newquest1;?></span>
        </button>
    </div>
    <div id="collapseOne1" class="accordion-collapse collapse" aria-labelledby="headingOne1"
        data-bs-parent="#accordionExample2">
        <div class="accordion-body">
            <?php echo $answe1;?>
        </div>
    </div>
</div>