<?php $order = Fenix::getCollection('checkout/order')->getOrderInfo() ?>
<?php $products = Fenix::getCollection('checkout/order')->getProducts() ?>
<?php $total = 0 ?>
<?php if ($products->count() > 0) { ?>

        <!-- OffCanvas Cart Start -->
        <div id="offcanvas-cart" class="offcanvas offcanvas-cart hover-style-furniture">
            <div class="inner">
                <div class="head">
                    <span class="title">Корзина</span>
                    <button class="offcanvas-close">×</button>
                </div>
                <div class="body customScroll">
                    <ul class="minicart-product-list">
                    <?php foreach ($products AS $i => $_product) { ?>
                        <?php $total += ($_product->getOrderUnitPrice() * $_product->getOrderQty()) ?>

                        <li>
                            <a href="<?php echo $_product->getUrl() ?>" class="image"><img
                                    src="<?php echo $_product->getImageAdapt(98, 98) ?>" alt="<?php echo $_product->getTitle() ?>"></a>
                            <div class="content">
                                <a href="<?php echo $_product->getUrl() ?>" class="title"><?php echo $_product->getTitle() ?></a>
                                <span class="quantity-price"><?php echo $_product->getOrderQty() ?> x <span class="amount"><?php echo $_product->getOrderUnitPrice() ?> UAH</span></span>
                                <a href="javascript: void(0);" onclick="return FenixCheckout.removeProduct(<?php echo $_product->getOrderUnitId() ?>)" class="remove">×</a>
                            </div>
                        </li>
                        <?php
                        }
                        ?>    
                    </ul>
                </div>
                <div class="shopping-cart-total">
                    <!--<h4>Subtotal : <span>$20.00</span></h4>
                    <h4>Shipping : <span>$7.00</span></h4>
                    <h4>Taxes : <span>$0.00</span></h4>-->
                    <h4 class="shop-total">Итого : <span><?php echo number_format($total, 2, ',', ''); ?> UAH</span></h4>
                </div>
                <div class="foot">
                    <div class="buttons">
                        <a href="cart.html" class="btn btn-dark btn-hover-primary mb-30px">view cart (допил)</a>
                        <a href="<?php echo $this->getUrl('checkout') ?>" class="btn btn-outline-dark current-btn"><?php echo Fenix::lang('Оформить заказ') ?></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- OffCanvas Cart End -->
        <?php } else { ?>
    <?php echo Fenix::getCreatorUI()->loadPlugin('Events')->appendClass(Creator_Events::TYPE_INFO)->setMessage("В корзине нет товаров")->fetch() ?>
            <!-- OffCanvas Cart Start -->
            <div id="offcanvas-cart" class="offcanvas offcanvas-cart hover-style-furniture">
            <div class="inner">
                <div class="head">
                    <span class="title">Корзина</span>
                    <button class="offcanvas-close">×</button>
                </div>
                <div class="body customScroll">
                    <ul class="minicart-product-list">
                    <?php echo Fenix::getCreatorUI()->loadPlugin('Events')->appendClass(Creator_Events::TYPE_INFO)->setMessage("В корзине нет товаров")->fetch() ?>
                    </ul>
                </div>

            </div>
        </div>
        <!-- OffCanvas Cart End -->
<?php } ?>