<div class="p-connect">
    <div class="container">
        <div class="row">
            <div class="video_col">
                <div class="connect__title">
                    <p class="p-connect__title"><?php echo Fenix::lang('Видео осмотр товара онлайн'); ?></p>
                    <p class="p-connect__description">
                        <?php echo Fenix::lang('Наши консультанты продемонстрируют интересующий товар находящийся в нашем магазине в режиме видеоконференции в Viber или Telegram'); ?>
                    </p>
                    <p class="p-connect__terms">
                        <?php echo Fenix::lang('Осмотр онлайн возможен в рабочие часы нашего магазина')?>
                    </p>
                </div>
                <div class="p-button">
                    <button class="nav-item homev7-pages roundbgcolor-box">
                        <a class="homev7-nav-link nav-link round-box" style="font-weight: 700;"
                            href="javascript:void(0)" data-bs-toggle="modal" data-bs-target="#doorvideos">
                            <?php echo Fenix::lang('Заказать видеоконсультацию')?></a>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>