<div class="std-block series-kit" style="margin:0">
    <ul class="ucp-menu">
        <li><a href="<?php echo $this->getUrl('customer/profile') ?>">Моя информация</a></li>
        <li><a href="<?php echo $this->getUrl('customer/favorites') ?>">Избранные товары</a></li>
        <li><a href="<?php echo $this->getUrl('customer/orders') ?>">Мои заказы</a></li>
        <li><a href="<?php echo $this->getUrl('session/logout') ?>">Выход</a></li>
    </ul>
</div>