<?php if ($this->Error != null): ?>
    <?php echo $this->render('creator/form/error.phtml') ?>
    <div class="gui-wysiwyg-error">
<?php endif ?>
<?php $textarea = null ?>
<?php if ($this->Plugin->getSplitByLang() === true): ?>
    <?php $lang = $this->Plugin->getLang() ?>
    <?php $name = $this->Plugin->getName() ?>
    <?php $id   = $this->Plugin->getName() ?>
    
    <?php $Tabs = $this->Plugin->loadPlugin('Tabs') ?>
    <?php $Tabs ->setId($name . '_tabs') ?>
    
    <?php foreach ($lang->getLanguagesList() AS $_lang): ?>
        
        <?php #$this->Plugin->appendStyle('padding-left:30px;') ?>
        <?php $this->Plugin->setName($name . '_' . $_lang->name) ?>
        <?php $this->Plugin->setId($id . '_' . $_lang->name) ?>
        <?php $this->Plugin->setValue($this->Plugin->getRequest()->getPost($this->Plugin->getName())) ?>

	    <script>
	        tinyMCE.init({
	            mode : "exact",
	            elements: "<?php echo $this->Plugin->getId() ?>",
	    
	            theme : "advanced",
	            plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,filemanager,imagemanager",
	    
	            // Theme options
	            theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
	            theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
	            theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
	            theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
	    
	            theme_advanced_toolbar_location : "top",
	            theme_advanced_toolbar_align : "left",
	            theme_advanced_statusbar_location : "bottom",
	            theme_advanced_resizing : true
	        });    
	    </script>
        
        <?php $Tabs->addTab($name . '_' . $_lang->name . '_tab', $_lang->label, '<textarea' . $this->Plugin->getAttributeSet('creator.form.wysiwyg') . '>' . $this->Plugin->getValue() . '</textarea>'); ?>
        
    <?php endforeach ?>
    	
    <?php $textarea = $Tabs->fetch() ?>
<?php else: ?>
    <script>
        tinyMCE.init({
            mode : "exact",
            elements: "<?php echo $this->Plugin->getId() ?>",
    
            theme : "advanced",
            plugins : "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,filemanager,imagemanager",
    
            // Theme options
            theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
    
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : true
        });    
    </script>
    <?php $textarea = '<textarea' . $this->Plugin->getAttributeSet('creator.form.wysiwyg') . '>' . $this->Plugin->getValue() . '</textarea>' ?>
<?php endif ?>


<?php if ($this->Plugin->getDetails() != null): ?>
    <div class="gui-field-details-container">
        <?php echo $textarea ?>
        <div class="gui-details"><?php echo $this->Plugin->getDetails() ?></div>
    </div>
<?php else: ?>
    <?php echo $textarea ?>
<?php endif ?>        
        
        
<?php if ($this->Error != null): ?>
    </div>
<?php endif ?>