<?php
if ( ! $this->article) {
    return '';
}
$article = $this->article;
$image = $article->getImageAdapt(450, 277);
$title = $article->getTitle();
$announce = $article->getContent();
$date = $article->getCreateDate();
?>

<div class="col-md-6" style="padding-bottom: 30px;">
    <div class="single-blog-post blog-grid-post">
        <div class="blog-post-media">
            <div class="blog-image">
                <a href="<?php echo $article->getUrl() ?>"><img class="lazyload" src="<?php echo $image; ?>" alt="<?php echo $title;?>" /></a>
            </div>
        </div>
        <div class="blog-post-content-inner mt-30">
            <h1 class="blog-title"><a href="<?php echo $article->getUrl() ?>"><?php echo $title; ?></a></h1>
            <ul class="blog-page-meta">
                <li>
                    <a href="<?php echo $article->getUrl() ?>"><i class="ion-calendar"></i><?php echo $date;?></a>
                </li>
            </ul>
            <p>
            <?php echo Fenix::getHelper('core/service_text')->characterLimiter(strip_tags($announce), 350); ?>
            </p>
            <a class="read-more-btn" href="<?php echo $article->getUrl() ?>"> <?php echo Fenix::lang('Подробнее')?> <i
                    class="ion-android-arrow-dropright-circle"></i></a>
        </div>
    </div>
    <!-- single blog post -->
</div>
