<div class="star-box">
                <span style="display: flex; align-items: center;">Ваша оценка:</span>
                <input type="hidden" name="rate" value="5" id="review-rate-value" />
                <div class="rating-product star-rating">
                    <i class="ion-android-star deactive"></i>
                    <i class="ion-android-star deactive"></i>
                    <i class="ion-android-star deactive"></i>
                    <i class="ion-android-star deactive"></i>
                    <i class="ion-android-star deactive"></i>
                </div>
            </div>


