<?php 
$searchurl = $_SERVER['REQUEST_URI'];
$region = urldecode(strstr($searchurl, '='));
    $region = str_replace('=Самоклейка ', '', $region);
    
    $maxprices = Fenix::getHelper('catalog/service_categories')->getMaxprice($this->category->id);
    $maxprices = mysqli_fetch_array($maxprices);
    $maxprices = array($maxprices);
    foreach ($maxprices as $max){
        $maxprice = $max['max'];
        
    }
    $minprices = Fenix::getHelper('catalog/service_categories')->getMinprice($this->category->id);
    $minprices = mysqli_fetch_array($minprices);
    $minprices = array($minprices);
    
    foreach ($minprices as $min){
        $minprice = $min['min'];
        
    }

/*Вопросы и ответы */
if (strpos($_SERVER['REQUEST_URI'], '/ua') !== false) { 
    $quest1 = 'Скільки коштує самоклейка в місті '. Fenix::lang($region) .'?';
    $answe1 = '<p>Вартість самоклейки в місті '. Fenix::lang($region) . ' від - ' .$minprice.'грн. за 1м погонний, до - ' .$maxprice.'грн. за рулон 15м.</p>';
    $quest2 = 'Де можна використовувати самоклейку?';
    $answe2 = '<p>Самоклейющуюся плівку можна використовувати для обклеювання меблів, столів, кухонного фартуха, стільниці, холодильника, підвіконня, і т.д. Так само є вітражна самоклейка для скла, самоклеюча плівка для малювання крейдою і дзеркальна самоклеюча плівка.</p>';
    $quest3 = 'Скільки часу займає доставка?';
    $answe3 = '<p>Швидкість доставки в місто '. Fenix::lang($region) .' залежить від часу замовлення і віддаленості від наших складів. Найчастіше доставка не перевищує 2 днів. Відправка замовлення здійснюється в день замовлення при оформленні його до 16.00 в будні, і до 12.00 у вихідні.</p>';
    $quest4 = 'Чи можу я купити 1м плівки і які бувають розміри?';
    $answe4 = '<p>Так! Ми відпускаємо самоклейку як рулонами так і кратно 0.5 метрів. Ширина плівки 45см, 67,5см, 90см.</p>';
} else {
$quest1 = 'Сколько стоит самоклейка в городе '. Fenix::lang($region) .'?';
$answe1 = '<p>Стоимость самоклейки в городе '. Fenix::lang($region) . ' от - ' .$minprice.'грн. за 1м погонный, до - ' .$maxprice.'грн. за рулон 15м.</p>';
$quest2 = 'Где можно использовать самоклейку?';
$answe2 = '<p>Самоклейющуюся пленку можно использовать для оклейки мебели, столов, кухонного фартука, столешницы, холодильника, подоконника, и т.д. Так же есть витражная самоклейка для стекла, самоклеющаяся пленка для рисования мелом и зеркальная самоклеющаяся пленка.</p>';
$quest3 = 'Сколько времени занимает доставка?';
$answe3 = '<p>Скорость доставки в город '. Fenix::lang($region) .' зависит от времени заказа и удаленности от наших складов. Чаще всего доставка не превышает 2 дней. Отправка заказа производится в день заказа при оформлении его до 16.00 в будни, и до 12.00 в выходные.</p>';
$quest4 = 'Могу ли я купить 1м пленки и какие бывают размеры?';
$answe4 = '<p>Да! Мы отпускаем самоклейку как рулонами так и кратно 0.5 метров. Ширина пленки 45см, 67,5см, 90см.</p>';
}
?>
<br>
<div class="voznikli" style="text-align: center;"><?php echo Fenix::lang('Ответы на часто задаваемые вопросы') ?></div>
<br>
<div itemscope itemtype="https://schema.org/FAQPage" class="accordion">
    <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question" class="trigger">
        <input type="checkbox" id="checkbox-1" name="checkbox-1" />
        <label for="checkbox-1" class="checkbox">
            <span itemprop="name"><?php echo '🥇' . $quest1;?></span><i></i>
        </label>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer" class="content">
            <div itemprop="text"><?php echo $answe1;?></div>
        </div>
    </div>
    <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question" class="trigger">
        <input type="checkbox" id="checkbox-2" name="checkbox-2" />
        <label for="checkbox-2" class="checkbox">
            <span itemprop="name"><?php echo '🥇' . $quest2;?></span><i></i>
        </label>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer" class="content">
            <div itemprop="text"><?php echo $answe2;?></div>
        </div>
    </div>
    <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question" class="trigger">
        <input type="checkbox" id="checkbox-3" name="checkbox-3" />
        <label for="checkbox-3" class="checkbox">
            <span itemprop="name"><?php echo '🥇' . $quest3;?></span><i></i>
        </label>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer" class="content">
            <div itemprop="text"><?php echo $answe3;?></div>
        </div>
    </div>
    <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question" class="trigger">
        <input type="checkbox" id="checkbox-4" name="checkbox-4" />
        <label for="checkbox-4" class="checkbox">
            <span itemprop="name"><?php echo '🥇' . $quest4;?></span><i></i>
        </label>
        <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer" class="content">
            <div itemprop="text"><?php echo $answe4;?></div>
        </div>
    </div>
    <?php

?>
</div>
<script src="https://dev.100dverei.com.ua/var/themes/modern171130/skin/js/faq.js"></script>