<?php $order = Fenix::getCollection('checkout/order')->getOrderInfo() ?>
<?php $products = Fenix::getCollection('checkout/order')->getProducts() ?>
<?php $total = 0 ?>
<?php if ($products->count() > 0) { ?>
<div class="table-content table-responsive cart-table-content offcanvas-cart">
    <!-------->
    <div id="checkinfotb">
        <?php 
        $totallistprice = $totallistprice + $total;
        foreach ($products as $i => $_product) {
                                                                if ($_product->getOrderPcsSale() == 1){
                                                                    if ($_product->getOrderQty() < 10){
                                                                        $UnitPrice = $_product->getOrderUnitPrice() ;
                                                                    } if ($_product->getOrderQty() >= 10){
                                                                        $UnitPrice = $_product->getOrderUnitPricePcs10() ;
                                                                    } if ($_product->getOrderQty() >= 30){
                                                                        $UnitPrice = $_product->getOrderUnitPricePcs30() ;
                                                                    }
                                                                } else {
                                                                    $UnitPrice = $_product->getOrderUnitPrice() ;
                                                                }
            
            ?>

        <?php 
                $total = 0;
                $total += ($UnitPrice * $_product->getOrderQty()) ?>
        <div class="tr_subtotal tr_product_<?php echo $_product->getOrderUnitId() ?>">
            <div class="main-product">
                <div class="product-thumbnail">
                    <a href="<?php echo $_product->getUrl() ?>"><img
                            src="<?php echo $_product->getImageAdapt(98, 98) ?>"
                            alt="<?php echo $_product->getTitle() ?>" /></a>
                </div>
                <div class="product-name"><a
                        href="<?php echo $_product->getUrl() ?>"><?php echo $_product->getTitle() ?></a></div>
                <div class="product-remove">
                    <a href="javascript: void(0);"
                        onclick="return FenixCheckout.removeProductCart(<?php echo $_product->getOrderUnitId() ?>)">×</a>
                </div>
            </div>
            <div class="footer-product">
                <div class="product-price-cart"><span><?php echo Fenix::lang('Цена') ?><?php echo ': ';?></span><span
                        class="amountcart_<?php echo $_product->getOrderUnitId() ?>"><?php echo $UnitPrice ?></span>
                    UAH</div>
                <div class="product-quantity">
                    <div class="qty-block">
                        <div onclick="return FenixCheckout.minusQtyCart($('#qty_<?php echo $_product->getOrderUnitId() ?>'), $('#price_<?php echo $_product->getOrderUnitId() ?>'), '<?php echo $_product->getOrderUnitId() ?>')"
                            class="dec qtybutton">-</div>
                        
                        <input tabindex="<?php echo $i + 1 ?>"
                            onkeyup="if (this.value < 0 || this.value == ''){return false;
									       } if (this.value > 10000){this.value=10000;
									       } if (this.value > 0 && this.value < 10000){FenixCheckout.updateCheckoutItemTotalCart($(this), $('#price_<?php echo $_product->getOrderUnitId() ?>'), '<?php echo $_product->getOrderUnitId() ?>');FenixCheckout.updateCheckoutTotalQtyCart()}"
                            class="checkout-item-qty" data-unitid="<?php echo $_product->getOrderUnitId() ?>"
                            data-unitprice="<?php echo $_product->getOrderUnitPrice() ?>"
                            data-unitprice="<?php echo $_product->getOrderUnitPrice() ?>"
                            data-unitprice10="<?php echo $_product->getOrderUnitPricePcs10() ?>"
                            data-unitprice30="<?php echo $_product->getOrderUnitPricePcs30() ?>"
                            data-sale="<?php echo $_product->getOrderPcsSale() ?>"
                            id="qty_<?php echo $_product->getOrderUnitId() ?>" type="text" name="qty[]"
                            value="<?php echo $_product->getOrderQty() ?>" />
                        <div onclick="return FenixCheckout.plusQtyCart($('#qty_<?php echo $_product->getOrderUnitId() ?>'), $('#price_<?php echo $_product->getOrderUnitId() ?>'), '<?php echo $_product->getOrderUnitId() ?>')"
                            class="inc qtybutton">+</div>
                        
                    </div>
                </div>
                <div class="product-subtotal"><?php echo Fenix::lang('Сумма') ?><?php echo ': ';?><span
                        class="product_subtotal_<?php echo $_product->getOrderUnitId() ?>"><?php echo number_format($total, 2, '.', ''); ?></span>
                    UAH</div>
            </div>
        </div>
        <?php 
    $totallistprice = $totallistprice + $total;
    } ?>
    </div>
    <!-------->
    <script>
  gtag("event", "begin_checkout", {
    currency: "UAH",
    value: <?php echo $totallistprice; ?>,
    items: [<?php
                $s = 0;
                foreach ($products as $i => $product) {
                    if ($s <= 0) {
                        $s++;
                        echo "{
				id: '" . $product->sku . "', \n
                item_id: '" . $product->sku . "', \n
				google_business_vertica : 'retail', \n
                item_name: '" . $product->title . "', \n
                item_list_id: '" . $product->parent . "',\n
                price: " . $product->price . " , \n
                currency: 'UAH', \n
                quantity: ". $product->getOrderQty() . " \n
                } ";
                    } else {
                        echo ", {
				id: '" . $product->sku . "', \n			
                item_id: '" . $product->sku . "', \n
				google_business_vertica : 'retail', \n
                item_name: '" . $product->title . "', \n
                item_list_id: '" . $product->parent . "',\n
                price: " . $product->price . " , \n
                currency: 'UAH', \n
                quantity: " . $product->getOrderQty() . " \n
                }";
                    }
                }
                ?>]
  });
</script>    
</div>
<?php } else { ?>
<?php echo Fenix::getCreatorUI()
        ->loadPlugin('Events')
        ->appendClass(Creator_Events::TYPE_INFO)
        ->setMessage("В корзине нет товаров")
        ->fetch() ?>
<?php } ?>