<div class="social-likes">
    <!-- Facebook -->
    <div id="fb-root"></div>
    <script>
        (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <div style="position: absolute; top: 2px; left: 5px;" class="fb-like" data-send="false" data-layout="button_count" data-width="85" data-show-faces="true" data-font="arial"></div>
    <!-- /Facebook -->

    <!-- Контакт -->
    <script type="text/javascript" src="https://userapi.com/js/api/openapi.js?49"></script>
    <script type="text/javascript">VK.init({apiId: 4046478, onlyWidgets: true});</script>
    <div style="position: absolute; top: 1px; left: 105px;" id="vk_like"></div>
    <script type="text/javascript">VK.Widgets.Like("vk_like", {type: "mini"});</script>
    <!-- /Контакт -->

    <!-- Твиттер -->
    <div style="position: absolute; left: 205px; top: 2px;">
        <a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>
    <!-- /Твиттер -->

    <!-- Гуглоплюс -->
    <div style="position: absolute; top: 0px; right: 0px;">
        <g:plusone align="right"></g:plusone>
    </div>
    <!-- /Гуглоплюс -->
</div>