<nav class="bottom-menu wrapper-980">
    <a href="<?php echo $this->getUrl() ?>">Главная</a>
    <a href="<?php echo $this->getUrl('about') ?>">О магазине</a>
    <a href="<?php echo $this->getUrl('pay') ?>">Оплата и доставка</a>
    <a href="<?php echo $this->getUrl('articles') ?>">Новости</a>
    <a href="<?php echo $this->getUrl('information') ?>">Полезная информация</a>
    <a href="<?php echo $this->getUrl('contacts') ?>">Контакты</a>
</nav>