<?php $this->headScript()->appendFile($this->getSkinUrl("js/fancybox/lib/jquery.mousewheel-3.0.6.pack.js")) ?>
<?php $this->headScript()->appendFile($this->getSkinUrl("js/fancybox/source/jquery.fancybox.js?v=2.0.6")) ?>
<?php $this->headLink()->appendStylesheet($this->getSkinUrl("js/fancybox/source/jquery.fancybox.css?v=2.0.7")) ?>
<?php $this->headScript()->appendFile($this->getSkinUrl("js/fancybox/source/helpers/jquery.fancybox-buttons.js?v=1.0.2")) ?>
<?php $this->headLink()->appendStylesheet($this->getSkinUrl("js/fancybox/source/helpers/jquery.fancybox-buttons.css?v=1.0.2")) ?>
<?php $this->headScript()->appendFile($this->getSkinUrl("js/fancybox/source/helpers/jquery.fancybox-thumbs.js?v=1.0.2")) ?>
<?php $this->headLink()->appendStylesheet($this->getSkinUrl("js/fancybox/source/helpers/jquery.fancybox-thumbs.css?v=1.0.2")) ?>
<?php $this->headScript()->appendFile($this->getSkinUrl("js/fancybox/source/helpers/jquery.fancybox-media.js?v=1.0.0")) ?>
