<?php echo $this->render("layout/html/breadcrumbs.phtml"); ?>
<section class="about-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mb-res-sm-50px">
                <div class="about-left-image">
                    <img src="/var/upload/exchange.png" alt="" class="img-responsive" />
                </div>
            </div>
            <div class="col-lg-6">
                <div class="about-content">
                    <div class="about-title">
                        <h1><?php echo $this->current->getSeo()->getH1() ?></h1>
                    </div>
                    <p class="mb-30px"></p>
                    <div style="line-height: 25pt;">
                    <p> <span style="font-size:20px">Закон о защите прав потребителя дает Вам право обменять или вернуть товар в течение 14 дней после совершения покупки.</span></p>

<p><span style="font-size:16px">Для того чтобы Вы могли воспользоваться этой возможностью Вам необходимо убедится в том что:</span></p>

<p><span style="font-size:16px">- товар полностью укомплектован.</span></p>

<p><span style="font-size:16px">- не нарушена целостность упаковки</span></p>

<p><span style="font-size:16px">- товар не имеет следов использования и не был в употреблении, а именно: без царапин, сколов, потертостей и т.д.</span></p>

<p><span style="font-size:16px">- на товаре сохранены ярлыки и заводская маркировка</span></p>

<p><span style="font-size:16px">Оплата служб доставки при возврате&nbsp;товара не по вине магазина оплачивает покупатель.</span></p>
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>