<div class="container wrapper-1000 reset-box" style="width:1010px">
    <section class="row">
        <?php if ($this->header != null): ?>
            <div class="col-md-12">
                <?php echo $this->header ?>
            </div>
        <?php endif ?>
        <aside class="col-lg-3">
            <?php echo $this->left ?>
        </aside>
        <article class="col-lg-9">
            <?php echo $this->center ?>
        </article>
    </section>
</div>