<?php
                $user_id = @$_COOKIE['_ga'];
                $user_id = str_replace ('GA', '', $user_id);
                
                
                $pieces = explode('.', $user_id);
                    // Get the last two pieces
                $user = array_slice($pieces, -2);
                    // Join them back using dot as delimiter and return
                $user_id = implode('.', $user);
$ratingproduct = $this->product->total_rating; 
$brandproduct = $this->product->brand_name;
//echo $brandproduct;
$titleproductthis = $this->product->getSeo()->getH1();
?>
<section class="product-detail" data-selector_name="<?php echo $this->product->title?>"
    data-selector_url="<?php echo Fenix::getUrl($this->product->url_key);?>"
    data-selector_img="<?php echo Fenix::getUploadImageUrl($this->product->image);?>">
    <?php echo $this->render("layout/html/breadcrumbs.phtml"); ?>
    <div class="container">
        <p class="h1"><?php echo $this->product->getSeo()->getH1() ?></p>

        <div class="row" itemscope itemtype="https://schema.org/Product">
            <span style="display: none;" itemprop="brand"><?php echo $brandproduct; ?></span>
            <div class="col-12 col-lg-6">
                <div class="product-slider-images">
                    <?php
					if($this->product->is_promo > 0) { ?>
                    <span class="product-widget sale"><?php echo Fenix::lang('Акция') ?></span>
                    <?php }
					if($this->product->real_foto > 0) { ?>
                    <span class="product-widget realfoto"><?php echo Fenix::lang('Фото в интерьере') ?></span>
                    <?php }
					
					if($this->product->is_bestseller > 0) { ?>
                    <span class="product-widget bestseller"><?php echo Fenix::lang('Хит продаж') ?></span>
                    <?php }
					
					if($this->product->is_new > 0) { ?>
                    <span class="product-widget new"><?php echo Fenix::lang('Новинка') ?></span>
                    <?php }
					
					if($this->product->is_discount > 0) { ?>
                    <span class="product-widget discount"><?php echo Fenix::lang('Скидки') ?></span>
                    <?php }
					
					$video = Fenix::getYouTubeVideoId(trim(strip_tags($this->product->video)));
					
					if($video != '') { ?>
                    <span class="product-widget video"><?php echo Fenix::lang('Есть видео') ?></span>
                    <?php }
					
					$imageMain = $this->product->getImageResize(600, 455, true);
					$nameImage = stristr($imageMain, 'no_image.png');
					
					$images = Fenix::getHelper('catalog/service_product')->setProduct($this->product)->getImages();
					?>
                    <div class="slider-for slider-product">
                        <?php if($imageMain && ($nameImage != 'no_image.png')) { ?>
                        <div>
                            <a href="<?php echo $this->product->getImageResize(1000, 1000, true) ?>">
                                <?php 
			$imgwebp1 = str_replace('.jpg', '.webp', $imageMain);
			if (file_exists(str_replace('https://dev.100dverei.com.ua', '/var/www/dverei/dev.100dverei.com.ua' , $imgwebp1))) { ?>
                                <picture style="margin: 0 auto;">
                                    <source type="image/webp" srcset="<?php echo $imgwebp1; ?>">
                                    <img itemprop="image" class="img-fluid rounded lazyload"
                                        src="<?php echo $this->product->getImageResize(560, 560, true); ?>"
                                        title="<?php echo $this->product->getSeo()->getH1() ?>"
                                        alt="<?php echo $this->product->getSeo()->getH1() ?>" />
                                </picture>
                                <?php } else { ?>
                                <img class="rounded img-fluid lazyload"
                                    src="<?php echo $this->product->getImageResize(560, 560, true); ?>"
                                    title="<?php echo $this->product->getSeo()->getH1() ?>"
                                    alt="<?php echo $titleProduct; ?>" />
                                <?php } ?>
                            </a>
                        </div>
                        <?php } else { ?>
                        <img src="<?php echo Fenix_Image::frame($nameImage, 600, 455); ?>" />
                        <?php } ?>
                        <?php $ii = 0; ?>
                        <?php foreach($images as $image) { ?>
                        <?php $ii++; ?>
                        <div>
                            <a href="<?php echo Fenix_Image::resizeWatermark($image->image, 1000, 1000) ?>">
                                <?php 
			$imgwebp2 = str_replace('.jpg', '.webp', Fenix_Image::resizeWatermark($image->image, 600, 455));
			if (file_exists(str_replace('https://dev.100dverei.com.ua', '/var/www/dverei/dev.100dverei.com.ua' , $imgwebp2))) { ?>
                                <picture style="margin: 0 auto;">
                                    <source type="image/webp" srcset="<?php echo $imgwebp2; ?>">
                                    <img src="<?php echo Fenix_Image::resizeWatermark($image->image, 600, 455); ?>"
                                        title="<?php echo $this->product->getSeo()->getH1() .' Изображение ' . $ii; ?>"
                                        alt="<?php echo $this->product->getSeo()->getH1() .' ' . $ii; ?>"
                                        class="img-fluid rounded lazyload">
                                </picture>
                                <?php } else { ?>
                                <img src="<?php echo Fenix_Image::resizeWatermark($image->image, 600, 455); ?>"
                                    title="<?php echo $this->product->getSeo()->getH1() .' Изображение ' . $ii; ?>"
                                    alt="<?php echo $this->product->getSeo()->getH1() .' ' . $ii; ?>"
                                    class="img-fluid rounded lazyload">
                                <?php } ?>
                            </a>
                        </div>
                        <?php } ?>
                    </div>
                    <?php if($imageMain && ($nameImage != 'no_image.png') && count($images) > 0) { ?>
                    <div class="slider-nav slider-product order-first d-none d-lg-block">
                        <div>
                            <?php 
			$imgwebp3 = str_replace('.jpg', '.webp', $this->product->getImageAdapt(187, 120));
			if (file_exists(str_replace('https://dev.100dverei.com.ua', '/var/www/dverei/dev.100dverei.com.ua' , $imgwebp3))) { ?>
                            <picture style="margin: 0 auto;">
                                <source type="image/webp" srcset="<?php echo $imgwebp3; ?>">
                                <img src="<?php echo $this->product->getImageAdapt(187, 120); ?>"
                                    class="rounded lazyload">
                            </picture>
                            <?php } else { ?>
                            <img src="<?php echo $this->product->getImageAdapt(187, 120); ?>"
                                class="rounded lazyload">
                            <?php } ?>

                        </div>
                        <?php foreach($images as $image) { ?>
                        <div>
                            <?php 
			$imgwebp4 = str_replace('.jpg', '.webp', Fenix_Image::adapt($image->image, 187, 120));
			if (file_exists(str_replace('https://dev.100dverei.com.ua', '/var/www/dverei/dev.100dverei.com.ua' , $imgwebp4))) { ?>
                            <picture style="margin: 0 auto;">
                                <source type="image/webp" srcset="<?php echo $imgwebp4; ?>">
                                <img src="<?php echo Fenix_Image::adapt($image->image, 187, 120); ?>"
                                    class="rounded lazyload">
                            </picture>
                            <?php } else { ?>
                            <img src="<?php echo Fenix_Image::adapt($image->image, 187, 120); ?>"
                                class="rounded lazyload">
                            <?php } ?>
                        </div>
                        <?php } ?>
                    </div>
                    <?php } ?>
                    <?php
					if($video != '') { ?>
                    <div class="product-video">
                        <a data-fancybox
                            href="https://www.youtube.com/watch?v=<?php echo $video; ?>"><?php echo Fenix::lang("Просмотреть видео") ?></a>
                    </div>
                    <?php } ?>
                </div>
                <?php
				if($video != '') { ?>
                <div class="product-video-mobile d-block d-lg-none">
                    <a data-fancybox
                        href="https://www.youtube.com/watch?v=<?php echo $video; ?>"><?php echo Fenix::lang("Просмотреть видео") ?></a>
                </div>
                <?php } ?>
            </div>
            <div class="col-12 col-lg-6">
                <h1 itemprop="name"><?php echo $this->product->getSeo()->getH1() ?></h1>
                <div class="row">
                    <div class="col-12 col-sm-4">
                        <?php
						$freeShipping = $this->product->free_shipping;
						if($freeShipping > 0) { ?>
                        <ul class="list-group">
                            <li class="list-group-item">
                                <span
                                    class="free-shipping text-uppercase d-inline-block"><?php echo Fenix::lang('Бесплатная доставка') ?></span>
                            </li>
                        </ul>
                        <?php } ?>
                    </div>
                    <div class="col-12 col-sm-4">
                        <ul class="list-group">
                            <li class="list-group-item"><b><?php echo Fenix::lang('Артикул:') ?></b> <span style="background: #4f95da;    font-weight: 900;    width: 70px;    display: inline-block;    text-align: center;"
                                    itemprop="sku"><span style="display: none;" itemprop="productID"><?php echo $this->product->getSku() ?></span><?php echo $this->product->getSku() ?></span></li>
                            <!--                            <li class="list-group-item">Размер:</li>-->
                        </ul>
                    </div>
                    <div class="col-12 col-sm-4">
                        <ul class="list-group">
                            <?php if($this->product->getInStock() & $this->product->getIsVisible() == '1'/*проверка на статус товара в наличии*/) { ?>
                            <li class="list-group-item in-stock">
                                <i class="icon-checkbox2"></i>
                                <?php echo Fenix::lang('Есть в наличии') ?>
                            </li>
                            <!--                                --><?php //if ($this->product->getDelivery() != '') { ?>
                            <!--                                    <li class="list-group-item">--><?php //echo $this->product->getDelivery() ?>
                            <!--</li>-->
                            <!--                                --><?php //} ?>
                            <?php } else { ?>
                            <li class="list-group-item"><?php echo Fenix::lang('Нет в наличии') ?></li>
                            <?php } ?>
                        </ul>
                    </div>
                    <div class="w-100"></div>
                    <div class="col-12 col-sm-6">
                        <div itemprop="offers" itemscope itemtype="https://schema.org/Offer">
                            <ul style="display: none;" itemprop="availability" href="https://schema.org/InStock"
                                class="list-group">
                                <?php if($this->product->getInStock()) { ?>
                                <li class="list-group-item in-stock">
                                    <i class="icon-checkbox2"></i>
                                    InStock
                                </li>
                                <!--                                --><?php //if ($this->product->getDelivery() != '') { ?>
                                <!--                                    <li class="list-group-item">--><?php //echo $this->product->getDelivery() ?>
                                <!--</li>-->
                                <!--                                --><?php //} ?>
                                <?php } else { ?>
                                <li class="list-group-item">OutOfStock</li>
                                <?php } ?>
                            </ul>
                            <link style="display: none;" itemprop="url"
                                href="<?php echo Fenix::getUrl($this->product->url_key);?>">
                            <?php
						$unit = $this->product->getUnit();
						if($this->product->price_old > 0) { ?>
                            <p class="old"><?php echo Fenix::getHelper('catalog/decorator')
							                               ->decoratePrice($this->product->price_old) ?></p>
                            <p itemprop="price" content="<?php echo $this->product->getPrice();?>" class="new"
                                data-selector_amount="<?php echo $this->product->getPrice();?>">
                                <?php echo Fenix::getHelper('catalog/decorator')
								                ->decoratePrice($this->product->getPrice()) ?>
                            </p>
                            <?php } else { ?>
                            <p itemprop="price" content="<?php echo $this->product->getPrice();?>" class="cost"
                                data-selector_amount="<?php echo $this->product->getPrice();?>">
                                <?php echo Fenix::getHelper('catalog/decorator')
								                ->decoratePrice($this->product->getPrice()) ?>
                            </p>
                            <?php } ?><span style="display: none;" itemprop="priceCurrency" content="UAH">грн</span>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6">
                        <?php if($this->product->getInStock() & $this->product->getIsVisible() == '1'/*проверка на статус товара в наличии*/) { ?>
                        <a class="btn btn-to-cart" href="#" role="button"
                            onclick="return FenixCheckout.addProduct('<?php echo $this->product->getBuy() ?>/qty/1')">
                            <i class="demo-icon icon-cart"></i>
                            <?php echo Fenix::lang('Добавить в корзину') ?>
                        </a>
                        <?php } else { ?>
                        <button class="btn btn-notify"
                            onclick="return FenixCheckout.notifyStockProduct(<?php echo $this->product->getId() ?>)">
                            <?php echo Fenix::lang('Уведомить о наличии') ?>
                        </button>
                        <?php } ?>

                    </div>
                    <?php if($this->product->getInStock() & $this->product->getIsVisible() == '1'/*проверка на статус товара в наличии*/) { ?>
                    <div class="w-100"></div>
                    <!--Счетчик -->
                    <!-- КОД ДЛЯ ВРЕМЕННОГО БАНЕРА ЕСЛИ АРТИКУЛ РАВЕН cent -->

                    <link rel="stylesheet" media="screen" href="schetchik/css/style.css" />
                    <script src="schetchik/js/newcountdown.js"></script>
                    <?php 
			if($this->product->is_promo > 0){ ?>
                    <div style="display: block; width: 100%; text-align: center; font-size: 20px;">
                        <?php echo Fenix::lang('До конца АКЦИИ:') ?></div><br>
                    <div id="CDT"></div>
                    <?php }
				?>
                    <div class="col-12">
                        <div class="bg-info rounded">
                            <div class="title"><?php echo Fenix::lang('Купить в 1 клик') ?></div>
                            <div class="text">
                                <?php echo Fenix::lang('Можно оставив свой номер телефона. Наш менеджер свяжется с Вами и уточнит детали заказа в ближайшее время') ?>
                            </div>
                            <?php echo Fenix::getHelper('checkout/forms')
								                ->getBuyOneClickForm($this->product->getId())
								                ->fetch(); ?>
                        </div>
                    </div>
                    <?php } ?>
                    <div class="w-100"></div>
                    <?php if($this->utpItems) { ?>
                    <div class="col-12">
                        <div class="row product-utp-container">
                            <?php foreach($this->utpItems as $utpItem) { ?>
                            <div class="col-12 col-sm-6 product-block-utp">
                                <div class="h4 text-uppercase">
                                    <?php echo $utpItem['title']; ?>
                                </div>
                                <div class="text"><?php echo $utpItem['content'] ?></div>
                                <?php
										if(isset($utpItem['image'])) { ?>
                                <div class="image">
                                    <img src="<?php echo $utpItem['image']; ?>">
                                </div>
                                <?php } ?>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="w-100"></div>
            <div class="col-12 col-lg-6">
                <?php
				$productDescription = Fenix::getHelper('catalog/service_product')
				                           ->setProduct($this->product)
				                           ->getContent();
				
				$chars = $this->product->getCardFeatures();
				?>
                <?php if(trim($productDescription != '') || !empty($chars)) { ?>
                <ul class="nav nav-tabs" id="productTab" role="tablist">
                    <?php if(trim($productDescription != '')) { ?>
                    <li class="nav-item">
                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#description" role="tab"
                            aria-controls="home" aria-selected="true"><?php echo Fenix::lang('Описание') ?>
                        </a>
                    </li>
                    <?php } ?>
                    <?php if(!empty($chars)) { ?>
                    <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#attributes" role="tab"
                            aria-controls="profile" aria-selected="false"><?php echo Fenix::lang('Характеристики') ?>
                        </a>
                    </li>
                    <?php } ?>
                </ul>
                <?php } ?>
                <?php if(trim($productDescription != '') || !empty($chars)) { ?>
                <div class="tab-content" id="productTabContent">
                    <?php if(trim($productDescription != '')) { ?>
                    <div class="tab-pane fade show active" id="description" role="tabpanel"
                        aria-labelledby="description">
                        <div class="inner-container" style="min-height: 50px;">
                            <div class="swiper-container">
                                <!--<div class="swiper-wrapper">-->

                                <!-- РАскрывающийся див-->
                                <div itemprop="description" id="opisanie">
                                    <?php 
                                //echo $productDescription; 
                                $h1text = $this->product->getSeo()->getH1();
                                $productDescription = str_replace ('<img', '<img class="lazyload"', $productDescription);
                                $productDescription = str_replace ('src="', 'src="', $productDescription);
                                $productDescription = str_replace ('%title%', $h1text, $productDescription);
                                echo $productDescription;
                           ?>
                                </div>

                                <!--</div>-->

                                <!-- Add Scroll Bar -->
                                <!--<div class="swiper-scrollbar"></div>-->
                            </div>
                            <button id="open"><?php echo Fenix::lang('Читать далее') ?></button>

                        </div>
                    </div>
                    <?php } ?>
                    <?php if(!empty($chars)) { ?>
                    <div class="tab-pane fade" id="attributes" role="tabpanel" aria-labelledby="attributes">
                        <div style="padding: 15px">
                            <table class="table table-striped">
                                <tbody>
                                    <?php foreach($chars as $char) {
											$charValue = trim($char->value);
											if($charValue == '') {
												continue;
											}
											?>
                                    <tr>
                                        <td><?php echo trim($char->name) ?></td>
                                        <td><?php echo $charValue ?></td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <?php } ?>
                </div>
                <?php } ?>
            </div>
            <div class="col-12 col-lg-6">
                <div class="header-reviews">
                    <div class="row">
                        <div class="col-4">
                            <p class="h4 text-uppercase"><?php echo Fenix::lang('Отзывы') ?></p>
                        </div>
                        <div class="col-8 text-right">
                            <a href="javascript:void(0);" role="button"
                                id="buttonSendReview"><?php echo Fenix::lang('Написать отзыв') ?></a>
                        </div>
                    </div>
                </div>
                <div class="forms">
                    <div class="container-form-review" id="reviewForm">
                        <?php echo $this->render('catalog/products/reviews/index.phtml') ?>
                    </div>
                </div>
                <div class="reviews">
                    <?php echo $this->render('catalog/products/reviews/list.phtml') ?>
                </div>
            </div>
            <!--призыв к действию -->
            <section style="display: flex; margin-top: 20px; width: 100%; " class="bg-light">
                <div style="text-align: center;" class="container">
                    <div class="voznikli">
                        <?php echo Fenix::lang('Возникли сложности при выборе товара?? Вам необходима консультация?') ?>
                    </div>
                    <br>
                    <div class="zadat">
                        <div class="zadatpotel"><?php echo Fenix::lang('Задайте вопрос по телефону:') ?> </div>
                        <div class="telefonchiki">
                            <a href="tel:0966418746"
                                class="list-group-item list-group-item-action operator kyivstar">(096)<b>
                                    641-87-46</b></a><br>
                            <a href="tel:0662815901"
                                class="list-group-item list-group-item-action operator vodafone">(066)<b>
                                    281-59-01</b></a><br>
                            <a href="tel:0934349243"
                                class="list-group-item list-group-item-action operator lifecell">(093)<b>
                                    434-92-43</b></a><br>
                        </div>
                    </div>
                    <div class="iliili">
                        <div class="ilivos"><?php echo Fenix::lang('Или воспользуйтесь услугой обратный звонок:') ?>
                        </div>
                        <div>
                            <a href="javascript: void(0);" class="callback text-uppercase"
                                onclick="FenixUI.callbackDialog()"><?php echo Fenix::lang('Оформить заявку на обратный звонок') ?></a>
                        </div>
                    </div>
                </div>
            </section>
            <?php
			//$relatedProducts = $this->product->getRelated();
			/*if($relatedProducts->count() > 0) { ?>

            <div class="w-100"></div>
            <div class="col related-products-container">
                <p class="h1"><?php echo Fenix::lang('Сопутствующие товары') ?></p>
                <div class="swiper-container related-products">
                    <div class="swiper-wrapper">
                        <?php foreach($relatedProducts AS $relatedProduct) { ?>
                        <div class="swiper-slide">
                            <?php echo $this->partial('catalog/products/block.phtml', ['product' => $relatedProduct]); ?>
                        </div>
                        <?php } ?>
                    </div>
                </div>
                <!-- Add Arrows -->
                <div class="product-viewed-next swiper-button-next">
                    <!--<i class="icon-arrow_right"></i>-->
                </div>
                <div class="product-viewed-prev swiper-button-prev">
                    <!-- <i class="icon-arrow_left"></i>-->
                </div>
            </div>
            <?php } */?>
            <?php echo $this->render('catalog/viewed.phtml'); ?>
        </div>
    </div>

    <!-- подписка в товарах-->

    <!-- подписка в товарах-->
    <!--	
	<section style="margin-top: 10px; "class="news-subscription">
    <div class="container rounded">
        <div class="row">
            <div class="col-12 col-md-7 first-column">
                <p style="font-size: 35px; color: #fff;"class="text-uppercase"><b>Подпишитесь на новости</b></p>
                <p class="h2">И получайте всегда только свежую и актуальную информацию</p>
				<p style="margin-top:35px;" class="h2">Подписались? Вводите при заказе промокод "NEWS" (в поле "КОММЕНТАРИЙ") и получайте <em style="color: red;">20грн</em> к заказу в подарок!</p>
            </div>
            <div class="col-12 col-md-5 second-column">
                <form id="subscribeForm">
                    <div class="row">
                        <div class="col w-75">
                            <input type="email" name="email" class="form-control form-control-lg"
                                   placeholder="Ваш email">
                        </div>
                        <div class="col-auto">
                            <button type="submit" class="btn btn-yellow"><i class="icon-letter"></i></button>
                        </div>
						
                    </div>
                </form>
<div style="margin-top: 10px; margin-left: 10px;">
						Пример ввода промокода:
						<img style="max-width: 300px;" src="prom.png" alt="Пример заполнения промокода"></p>
						</div>
                <script>
                    $(function () {
                        $("#subscribeForm").validate({
                            rules: {
                                email: {
                                    email: true,
                                    required: true
                                }
                            },
                            messages: {
                                email: "Введите email"
                            },
                            ignore: "div:hidden input, div:hidden select",
                            submitHandler: function () {
                                $.ajax({
                                    type: "POST",
                                    url: "<?php echo Fenix::getUrl('customer/subscriber/subscribe');?>",
                                    data: {
                                        email: $("#subscribeForm input[type='email']").val()
                                    },
                                    success: function (responseText) {
                                        if (responseText == 0) {
                                            $("#subscribeForm input[type='email']").after("<label for='email' class='error'></label>");
                                            $('#subscribeForm .error').html('Данный email уже существует в нашей базе!');
                                        }
                                        else {
                                            $('#subscribeForm').html(responseText);
                                        }

                                    },
                                    error: function (jqXHR, text, error) {
                                        $('#subscribeForm .error').html('Данный email уже существует в нашей базе!');
                                    }
                                });
                                return false;
                            }
                        });
                    });
                </script>
            </div>
        </div>
    </div>
</section> -->

    <?php if(stripos($_SERVER['HTTP_REFERER'], $_SERVER['HTTP_HOST']) !== false) { ?>
    <div class="container d-block d-md-none">
        <button onclick="history.back(); return false;" class="btn btn-back rounded">&laquo;
            <?php echo Fenix::lang('назад') ?></button>
    </div>
    <?php } ?>
</section>
<?php
$productCost = $this->product->price;
if($this->product->price_old > 0) {
	$productCost = $this->product->price_old;
}
?>
<script>
gtag('event', 'view_item', {
    currency: 'UAH',
    items: [{
		id: '<?php echo $this->product->sku; ?>',
        item_id: '<?php echo $this->product->sku; ?>',
        item_name: '<?php echo $titleProduct; ?>',
        price: <?php echo $this->product->getPrice(); ?>,
        currency: 'UAH',
        quantity: 1
    }],
    value: <?php echo $this->product->getPrice(); ?>
});
</script>
<script>
    gtag('event', 'page_view', {
  ecomm_pagetype: 'product',
  ecomm_prodid: <?php echo $this->product->sku; ?>,
  ecomm_totalvalue: <?php echo $this->product->getPrice(); ?>,
  isSaleItem: <?php if ($this->product->price_old > 0) { 
echo 'true';
  } else {
      echo 'false';
  }?>
});
</script>
<script>
gtag('event', 'page_view', {
  dynx_itemid: '<?php echo $this->product->sku; ?>',
  dynx_pagetype: 'offerdetail',
  dynx_totalvalue: <?php echo $this->product->getPrice(); ?>
});
</script>
<script>
$(function() {
    $("#buttonSendReview").click(function() {
        $('#reviewForm').dialog({
            width: 640,
            modal: true,
            title: 'Написать отзыв',
            open: function() {
                $('.ui-widget-overlay').click(function() {
                    $('#reviewForm').dialog('close');
                });
            }
        });
    });
});

carrotquest.track('$product_viewed', {
    "$name": "<?php echo $this->product->title;?>",
    "$url": "<?php echo Fenix::getUrl($this->product->getUrl());?>",
    "$amount": "<?php echo $productCost;?>",
    "$img": "<?php echo Fenix::getUploadImageUrl($this->product->image);?>",
});
carrotquest.identify([{
    op: "union",
    key: "$viewed_products",
    value: "<?php echo $this->product->title;?>"
}]);
</script>