<?php
$ratingproduct = $this->product->total_rating; 
$brandproduct = $this->product->brand_name;
//echo $brandproduct;
?>
<section class="product-detail" data-selector_name="<?php echo $this->product->title?>"
    data-selector_url="<?php echo Fenix::getUrl($this->product->url_key);?>"
    data-selector_img="<?php echo Fenix::getUploadImageUrl($this->product->image);?>">
    <?php echo $this->render("layout/html/breadcrumbs.phtml"); ?>
    <div class="container">
        <p class="h1"><?php echo $this->product->getSeo()->getH1() ?></p>

        <div class="row" itemscope itemtype="https://schema.org/Product">
            <span style="display: none;" itemprop="brand"><?php echo $brandproduct; ?></span>
            <div class="col-12 col-lg-6">
                <div class="product-slider-images">
                    <?php
                    if ($this->product->is_promo > 0) { ?>
                    <span class="product-widget sale"><?php echo Fenix::lang('Акция') ?></span>
                    <?php }
					if($this->product->real_foto > 0) { ?>
                    <span class="product-widget realfoto"><?php echo Fenix::lang('Фото в интерьере') ?></span>
                    <?php }
                    if ($this->product->is_bestseller > 0) { ?>
                    <span class="product-widget bestseller"><?php echo Fenix::lang('Хит продаж') ?></span>
                    <?php }

                    if ($this->product->is_new > 0) { ?>
                    <span class="product-widget new"><?php echo Fenix::lang('Новинка') ?></span>
                    <?php }

                    if ($this->product->is_discount > 0) { ?>
                    <span class="product-widget discount"><?php echo Fenix::lang('Скидки') ?></span>
                    <?php }

                    $video = Fenix::getYouTubeVideoId(trim(strip_tags($this->product->video)));

                    if ($video != '') { ?>
                    <span class="product-widget video"><?php echo Fenix::lang('Есть видео') ?></span>
                    <?php }

                    $imageMain = $this->product->getImageResize(600, 455, true);
                    $nameImage = stristr($imageMain, 'no_image.png');

                    $images = Fenix::getHelper('catalog/service_product')->setProduct($this->product)
                        ->getImages();
                    ?>
                    <div class="slider-for slider-product">
                        <?php if($imageMain && ($nameImage != 'no_image.png')) { ?>
                        <div>
                            <a href="<?php echo $this->product->getImageResize(1000, 1000, true) ?>">
                                <?php 
			$imgwebp1 = str_replace('.jpg', '.webp', $imageMain);
			if (file_exists(str_replace('https://dev.100dverei.com.ua', '/var/www/dverei/dev.100dverei.com.ua' , $imgwebp1))) { ?>
                                <picture style="margin: 0 auto;">
                                    <source type="image/webp" srcset="<?php echo $imgwebp1; ?>">
                                    <img itemprop="image" class="img-fluid rounded lazyload"
                                        src="<?php echo $this->product->getImageResize(600, 455, true); ?>"
                                        title="<?php echo $this->product->getSeo()->getH1() ?>"
                                        alt="<?php echo $this->product->getSeo()->getH1() ?>" />
                                </picture>
                                <?php } else { ?>
                                <img class="rounded img-fluid lazyload"
                                    src="<?php echo $this->product->getImageResize(600, 455, true); ?>"
                                    title="<?php echo $this->product->getSeo()->getH1() ?>"
                                    alt="<?php echo $titleProduct; ?>" />
                                <?php } ?>
                            </a>
                        </div>
                        <?php } else { ?>
                        <img src="<?php echo Fenix_Image::frame($nameImage, 600, 455); ?>" />
                        <?php } ?>
                        <?php $ii = 0; ?>
                        <?php foreach($images as $image) { ?>
                        <?php $ii++; ?>
                        <div>
                            <a href="<?php echo Fenix_Image::resizeWatermark($image->image, 1000, 1000) ?>">
                                <?php 
			$imgwebp2 = str_replace('.jpg', '.webp', Fenix_Image::resizeWatermark($image->image, 600, 455));
			if (file_exists(str_replace('https://dev.100dverei.com.ua', '/var/www/dverei/dev.100dverei.com.ua' , $imgwebp2))) { ?>
                                <picture style="margin: 0 auto;">
                                    <source type="image/webp" srcset="<?php echo $imgwebp2; ?>">
                                    <img src="<?php echo Fenix_Image::resizeWatermark($image->image, 600, 455); ?>"
                                        title="<?php echo $this->product->getSeo()->getH1() .' ' . $ii; ?>"
                                        alt="<?php echo $this->product->getSeo()->getH1() .' Изображение ' . $ii; ?>"
                                        class="img-fluid rounded lazyload">
                                </picture>
                                <?php } else { ?>
                                <img src="<?php echo Fenix_Image::resizeWatermark($image->image, 600, 455); ?>"
                                    title="<?php echo $this->product->getSeo()->getH1() .' ' . $ii; ?>"
                                    alt="<?php echo $this->product->getSeo()->getH1() .' Изображение ' . $ii; ?>"
                                    class="img-fluid rounded lazyload">
                                <?php } ?>
                            </a>
                        </div>
                        <?php } ?>
                    </div>
                    <?php if ($imageMain && ($nameImage != 'no_image.png') && count($images) > 0) { ?>
                    <div class="slider-nav slider-product order-first d-none d-lg-block">
                        <div>
                            <img src="<?php echo $this->product->getImageAdapt(187, 120); ?>" class="rounded">
                        </div>
                        <?php foreach ($images as $image) { ?>
                        <div><img src="<?php echo Fenix_Image::adapt($image->image, 187, 120); ?>" class="rounded">
                        </div>
                        <?php } ?>
                    </div>
                    <?php } ?>
                    <?php
                    if ($video != '') { ?>
                    <div class="product-video">
                        <a data-fancybox
                            href="https://www.youtube.com/watch?v=<?php echo $video; ?>"><?php echo Fenix::lang("Просмотреть видео") ?></a>
                    </div>
                    <?php } ?>
                </div>
                <?php
                if ($video != '') { ?>
                <div class="product-video-mobile d-block d-lg-none">
                    <a data-fancybox
                        href="https://www.youtube.com/watch?v=<?php echo $video; ?>"><?php echo Fenix::lang("Просмотреть видео") ?></a>
                </div>
                <?php } ?>
            </div>
            <div class="col-12 col-lg-6">
                <h1 itemprop="name"><?php echo $this->product->getSeo()->getH1() ?></h1>
                <div class="row">
                    <div class="col-12 col-sm-4">
                        <?php
                        $freeShipping = $this->product->free_shipping;
                        if ($freeShipping > 0) { ?>
                        <ul class="list-group">
                            <li class="list-group-item">
                                <span
                                    class="free-shipping text-uppercase d-inline-block"><?php echo Fenix::lang('Бесплатная доставка') ?></span>
                            </li>
                        </ul>
                        <?php } ?>
                    </div>
                    <div class="col-12 col-sm-4">
                        <ul class="list-group">
                            <li class="list-group-item"><b><?php echo Fenix::lang('Артикул:') ?></b> <span style="background: #4f95da;    font-weight: 900;    width: 70px;    display: inline-block;    text-align: center;"
                                    itemprop="sku"><span style="display: none;" itemprop="productID"><?php echo $this->product->getSku() ?></span><?php echo $this->product->getSku() ?></span></li>
                            <!--                            <li class="list-group-item">Размер:</li>-->
                        </ul>
                    </div>
                    <div class="col-12 col-sm-4">
                        <ul class="list-group">
                            <?php if($this->product->getInStock()) { ?>
                            <li class="list-group-item in-stock">
                                <i class="icon-checkbox2"></i>
                                <?php echo Fenix::lang('Есть в наличии') ?>
                            </li>
                            <!--                                --><?php //if ($this->product->getDelivery() != '') { ?>
                            <!--                                    <li class="list-group-item">--><?php //echo $this->product->getDelivery() ?>
                            <!--</li>-->
                            <!--                                --><?php //} ?>
                            <?php } else { ?>
                            <li class="list-group-item"><?php echo Fenix::lang('Нет в наличии') ?></li>
                            <?php } ?>
                        </ul>
                    </div>
                    <div class="w-100"></div>
                    <div class="col-12 col-sm-6">
                        <div itemprop="offers" itemscope itemtype="https://schema.org/Offer">
                            <ul style="display: none;" itemprop="availability" href="https://schema.org/InStock"
                                class="list-group">
                                <?php if($this->product->getInStock()) { ?>
                                <li class="list-group-item in-stock">
                                    <i class="icon-checkbox2"></i>
                                    InStock
                                </li>
                                <!--                                --><?php //if ($this->product->getDelivery() != '') { ?>
                                <!--                                    <li class="list-group-item">--><?php //echo $this->product->getDelivery() ?>
                                <!--</li>-->
                                <!--                                --><?php //} ?>
                                <?php } else { ?>
                                <li class="list-group-item">OutOfStock</li>
                                <?php } ?>
                            </ul>
                            <link style="display: none;" itemprop="url"
                                href="<?php echo Fenix::getUrl($this->product->url_key);?>">
                            <?php
                        $unit = $this->product->getUnit();
                        if ($this->product->price_old > 0) { ?>
                            <p class="old">
                                <?php echo Fenix::getHelper('catalog/decorator')->decoratePrice($this->product->price_old) ?>
                            </p>
                            <p itemprop="price" content="<?php echo $this->product->getPrice();?>" class="new"
                                data-selector_amount="<?php echo $this->product->getPrice();?>">
                                <?php echo Fenix::getHelper('catalog/decorator')->decoratePrice($this->product->getPrice()) ?><?php echo $unit ?>
                            </p>
                            <?php } else { ?>
                            <p itemprop="price" content="<?php echo $this->product->getPrice();?>" class="cost"
                                data-selector_amount="<?php echo $this->product->getPrice();?>">
                                <?php echo Fenix::getHelper('catalog/decorator')->decoratePrice($this->product->getPrice()) ?><?php echo $unit ?>
                            </p>
                            <?php } ?><span style="display: none;" itemprop="priceCurrency" content="UAH">грн</span>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6">
                        <?php if ($this->product->getInStock()) { ?>
                        <a class="btn btn-to-cart" href="#" role="button"
                            onclick="return FenixCheckout.addProduct('<?php echo $this->product->getBuy() ?>/qty/1')">
                            <i class="demo-icon icon-cart"></i> <?php echo Fenix::lang('Добавить в корзину') ?></a>
                        <?php } else { ?>
                        <button class="btn btn-notify"
                            onclick="return FenixCheckout.notifyStockProduct(<?php echo $this->product->getId() ?>)">
                            <?php echo Fenix::lang('Уведомить о наличии') ?>
                        </button>
                        <?php } ?>

                    </div>
                    <?php if ($this->product->getInStock()) { ?>
                    <div class="w-100"></div>
                    <div class="col-12">
                        <div class="bg-info rounded">
                            <div class="title"><?php echo Fenix::lang('Купить в 1 клик') ?></div>
                            <div class="text">
                                <?php echo Fenix::lang('Можно оставив свой номер телефона. Наш менеджер свяжется с Вами и уточнит детали заказа в ближайшее время') ?>
                            </div>
                            <?php echo Fenix::getHelper('checkout/forms')->getBuyOneClickForm($this->product->getId())->fetch(); ?>
                        </div>
                    </div>
                    <?php } ?>
                    <div class="w-100"></div>
                    <?php if ($this->utpItems) { ?>
                    <div class="col-12">
                        <div class="row product-utp-container">
                            <?php foreach ($this->utpItems as $utpItem) { ?>
                            <div class="col-12 col-sm-6 product-block-utp">
                                <div class="h4 text-uppercase">
                                    <?php echo $utpItem['title']; ?>
                                </div>
                                <div class="text"><?php echo $utpItem['content'] ?></div>
                                <?php
                                        if (isset($utpItem['image'])) { ?>
                                <div class="image">
                                    <img src="<?php echo $utpItem['image']; ?>">
                                </div>
                                <?php } ?>
                            </div>
                            <?php } ?>
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
            <div class="w-100"></div>
            <div class="col-12 col-lg-6">
                <?php
                $productDescription = Fenix::getHelper('catalog/service_product')->setProduct($this->product)
                    ->getContent();

                $chars = $this->product->getCardFeatures();
                ?>
                <?php if (trim($productDescription != '') || ! empty($chars)) { ?>
                <ul class="nav nav-tabs" id="productTab" role="tablist">
                    <?php if (trim($productDescription != '')) { ?>
                    <li class="nav-item">
                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#description" role="tab"
                            aria-controls="home" aria-selected="true">Описание</a>
                    </li>
                    <?php } ?>
                    <?php if ( ! empty($chars)) { ?>
                    <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#attributes" role="tab"
                            aria-controls="profile" aria-selected="false">Характеристики</a>
                    </li>
                    <?php } ?>
                </ul>
                <?php } ?>
                <?php if (trim($productDescription != '') || ! empty($chars)) { ?>
                <div class="tab-content" id="productTabContent">
                    <?php if (trim($productDescription != '')) { ?>
                    <div class="tab-pane fade show active" id="description" role="tabpanel"
                        aria-labelledby="description">
                        <div class="inner-container" style="height: 390px">
                            <div class="swiper-container">
                                <div class="swiper-wrapper">
                                    <div itemprop="description" class="swiper-slide">
                                        <?php 

									$seotext = str_replace ('<img', '<img class="lazyload"', $productDescription);
                                    $seotext = str_replace ('src="', 'src="', $seotext);
									echo $seotext;
												?>
                                    </div>
                                </div>
                                <!-- Add Scroll Bar -->
                                <div class="swiper-scrollbar"></div>
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                    <?php if ( ! empty($chars)) { ?>
                    <div class="tab-pane fade" id="attributes" role="tabpanel" aria-labelledby="attributes">
                        <div style="padding: 15px">
                            <table class="table table-striped">
                                <tbody>
                                    <?php foreach ($chars as $char) {
                                            $charValue = trim($char->value);
                                            if ($charValue == '') {
                                                continue;
                                            }
                                            ?>
                                    <tr>
                                        <td><?php echo trim($char->name) ?></td>
                                        <td><?php echo $charValue ?></td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <?php } ?>
                </div>
                <?php } ?>
            </div>

            <?php
            $serviceStructure = Fenix::getHelper('core/service_structure');
            $textureList = $serviceStructure->getPageGallery('texture-wallpaper');
            if (count($textureList) > 0) { ?>
            <div class="col-12 col-lg-6 wallpaper">
                <div class="header-reviews">
                    <p class="h4 text-uppercase"><?php echo $serviceStructure->getPageTitle(); ?></p>
                </div>

                <div class="row mt-3">
                    <?php foreach ($textureList as $texture) {
                            $title = '';
                            if (isset($texture['meta_title'])) {
                                $title = $texture['meta_title'];
                            }
                            ?>
                    <div class="col-12 col-md-3 mb-3 text-center">
                        <a href="<?php echo $texture['image_big']; ?>" data-fancybox="images"
                            data-caption="<?php echo $title; ?>">
                            <?php 
											
											$imgtexture = str_replace('https://dev.100dverei.com.ua/home/', '' , $texture['small_image']);
											$imgtexturewebp = str_replace('.jpg', '.webp', $texture['small_image']);
											if (file_exists(str_replace('https://dev.100dverei.com.ua', '/var/www/dverei/dev.100dverei.com.ua' , $imgtexturewebp))) {?>
                            <picture class="img-fluid rounded-circle lazyload">
                                <source type="image/webp" srcset="<?php echo $imgtexturewebp; ?>">
                                <img class="img-fluid rounded-circle lazyload"
                                    src="<?php echo $texture['small_image'] ; ?>" alt="<?php echo $title; ?>">
                            </picture>
                            <?php } else {?>

                            <img src="<?php echo $texture['small_image']; ?>"
                                class="img-fluid rounded-circle lazyload"><span><?php echo $title; ?></span>
                        </a>
                        <?php 
											}
											?>
                    </div>
                    <?php } ?>
                </div>
            </div>
            <!--призыв к действию -->
            <section style="display: flex; margin-top: 20px; width: 100%; " class="bg-light">
                <div style="text-align: center;" class="container">
                    <div class="voznikli">
                        <?php echo Fenix::lang('Возникли сложности при выборе товара?? Вам необходима консультация?') ?>
                    </div><br>
                    <div class="zadat">
                        <div class="zadatpotel"><?php echo Fenix::lang('Задайте вопрос по телефону:') ?> </div>
                        <div class="telefonchiki">
                            <a href="tel:0966418746"
                                class="list-group-item list-group-item-action operator kyivstar">(096)<b>
                                    641-87-46</b></a><br>
                            <a href="tel:0662815901"
                                class="list-group-item list-group-item-action operator vodafone">(066)<b>
                                    281-59-01</b></a><br>
                            <a href="tel:0934349243"
                                class="list-group-item list-group-item-action operator lifecell">(093)<b>
                                    434-92-43</b></a><br>
                        </div>
                    </div>
                    <div class="iliili">
                        <div class="ilivos"><?php echo Fenix::lang('Или воспользуйтесь услугой обратный звонок:') ?>
                        </div>
                        <div>
                            <a href="javascript: void(0);" class="callback text-uppercase"
                                onclick="FenixUI.callbackDialog()"><?php echo Fenix::lang('Оформить заявку на обратный звонок') ?></a>
                        </div>
                    </div>
                </div>
            </section>
            <?php } ?>
            <?php
            $relatedProducts = $this->product->getRelated();
            if ($relatedProducts->count() > 0) { ?>

            <div class="w-100"></div>
            <div class="col related-products-container">
                <p class="h1">Сопутствующие товары</p>
                <div class="swiper-container related-products">
                    <div class="swiper-wrapper">
                        <?php foreach ($relatedProducts AS $relatedProduct) { ?>
                        <div class="swiper-slide">
                            <?php echo $this->partial('catalog/products/block.phtml', ['product' => $relatedProduct]); ?>
                        </div>
                        <?php } ?>
                    </div>
                </div>
                <!-- Add Arrows -->
                <div class="product-viewed-next swiper-button-next"><i class="icon-arrow_right"></i></div>
                <div class="product-viewed-prev swiper-button-prev"><i class="icon-arrow_left"></i></div>
            </div>
            <?php } ?>
            <?php echo $this->render('catalog/viewed.phtml'); ?>
        </div>
    </div>
    <!-- подписка в товарах-->
    <!--
	<section style="margin-top: 10px; "class="news-subscription">
    <div class="container rounded">
        <div class="row">
            <div class="col-12 col-md-7 first-column">
                <p style="font-size: 35px; color: #fff;"class="text-uppercase"><b>Подпишитесь на новости</b></p>
                <p class="h2">И получайте всегда только свежую и актуальную информацию</p>
				<p style="margin-top:35px;" class="h2">Подписались? Вводите при заказе промокод "NEWS" (в поле "КОММЕНТАРИЙ") и получайте <em style="color: red;">20грн</em> к заказу в подарок!</p>
            </div>
            <div class="col-12 col-md-5 second-column">
                <form id="subscribeForm">
                    <div class="row">
                        <div class="col w-75">
                            <input type="email" name="email" class="form-control form-control-lg"
                                   placeholder="Ваш email">
                        </div>
                        <div class="col-auto">
                            <button type="submit" class="btn btn-yellow"><i class="icon-letter"></i></button>
                        </div>
						
                    </div>
                </form>
<div style="margin-top: 10px; margin-left: 10px;">
						Пример ввода промокода:
						<img style="max-width: 300px;" src="prom.png" alt="Пример заполнения промокода"></p>
						</div>
                <script>
                    $(function () {
                        $("#subscribeForm").validate({
                            rules: {
                                email: {
                                    email: true,
                                    required: true
                                }
                            },
                            messages: {
                                email: "Введите email"
                            },
                            ignore: "div:hidden input, div:hidden select",
                            submitHandler: function () {
                                $.ajax({
                                    type: "POST",
                                    url: "<?php echo Fenix::getUrl('customer/subscriber/subscribe');?>",
                                    data: {
                                        email: $("#subscribeForm input[type='email']").val()
                                    },
                                    success: function (responseText) {
                                        if (responseText == 0) {
                                            $("#subscribeForm input[type='email']").after("<label for='email' class='error'></label>");
                                            $('#subscribeForm .error').html('Данный email уже существует в нашей базе!');
                                        }
                                        else {
                                            $('#subscribeForm').html(responseText);
                                        }

                                    },
                                    error: function (jqXHR, text, error) {
                                        $('#subscribeForm .error').html('Данный email уже существует в нашей базе!');
                                    }
                                });
                                return false;
                            }
                        });
                    });
                </script>
            </div>
        </div>
    </div>
</section> -->
    <?php if (stripos($_SERVER['HTTP_REFERER'], $_SERVER['HTTP_HOST']) !== false) { ?>
    <div class="container d-block d-md-none">
        <button onclick="history.back(); return false;" class="btn btn-back rounded">&laquo; назад</button>
    </div>
    <?php } ?>
</section>
<script>
$(function() {
    $("#buttonSendReview").click(function() {
        $('#reviewForm').dialog({
            width: 640,
            modal: true,
            title: 'Написать отзыв',
            open: function() {
                $('.ui-widget-overlay').click(function() {
                    $('#reviewForm').dialog('close');
                });
            }
        });
    });
});
</script>